version: '3.1'

services:

  drupal:
    image: dismorfo/media:latest
    ports:
      - 8000:80
    volumes:
      - ./drupal:/var/www/html
      - ./drush-6.3.0:/drush
    restart: always
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025

  mailhog:
    image: mailhog/mailhog

  db:
    image: mariadb:latest
    restart: always
    stop_grace_period: 30s
    ports:
      - 3306
    volumes:
      - ./database/${MYSQL_DUMP_NAME}:/docker-entrypoint-initdb.d/${MYSQL_DUMP_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: ${ADMINER_DESIGN}
